adding 10up package and WIP - just paragraph thus far
hpuit/hpu-blocks-core pull request #3
Opened 2024-07-22 19:25 UTC by rayflores

I added one package for functionality and registration of  ( make it easier ).  Also, this is WIP for just the paragraph at the moment... regard this as a POC.  This currently works on the `core/paragraph` block only.  

Rebuild by:
`npm install`
then
`npm run build`

2024-07-22 20:33 UTC, iwatkinshpu approved these changes

2024-07-23 10:07 UTC, dswebsme requested changes
@rayflores Most of what the original developer did with this code base was shared as a large completed code base with many WordPress coding standards excluded. As a development team, we've adopted those standards and try to ensure new code adheres as much as possible. I cited several examples here to get you started but please review the code I didn't comment on as well. I'm sure there will be unmentioned examples where WordPress coding standards for both PHP and JS could be applied. Thanks!

2024-07-23 10:07 UTC, dswebsme commented on src/selector.js
> +        }
Spacing.

2024-07-23 10:07 UTC, dswebsme commented on src/selector.js
> +    });
Spacing.

2024-07-23 17:54 UTC, rayflores commented
@dswebsme I fixed the modified ( and surrounding ) formats and ran it through both the linter and code sniffer... All should be good.

2024-07-24 09:26 UTC, dswebsme approved these changes
@rayflores Approved. Just 1 item of note for future consideration. Looks great overall. Thanks!

2024-07-24 09:26 UTC, dswebsme commented on hpu-blocks-core.php
> +				'src' => $src,
Consider:
```
'handle' => 'hpu-blocks-core-editor-styles',
'src'    => $src,
```
             ^ vertically aligned array values

2024-07-24 14:04 UTC, merged