Remove standard block settings and some formatting
hpuit/hpu-blocks-core pull request #4
Opened 2024-07-30 00:27 UTC by rayflores

2024-07-30 00:31 UTC, rayflores commented
The panel is not easily removed, however, I was able to remove the actual settings...
![typography](https://github.com/user-attachments/assets/3dc4c6e1-5784-471d-ad2c-a585ce93ce51)

2024-07-30 22:34 UTC, dswebsme requested changes

2024-07-30 22:34 UTC, dswebsme commented on hpu-blocks-core.php
> +function disable_drop_cap_editor_settings( array $editor_settings ): array {
For functions that exist in the global namespace we should include a prefix as part of our naming conventions. It looks like surrounding functions may already be using `hpu_` so I recommend we keep it consistent here.

2024-07-30 22:34 UTC, dswebsme commented on hpu-blocks-core.php
> +add_filter( 'block_editor_settings_all', 'disable_drop_cap_editor_settings' );
Same as previous comment, this time in reference to the `callback` string being updated to reflect the `hpu_` naming prefix.

2024-07-30 22:34 UTC, dswebsme commented on src/block-variations/paragraph/index.js
> +	// );
Recommend removing commented code unless this is just a temporary removal and it will be restored in the near future. Even still, version control excels at restoring removed code on demand so removing is still a best practice.

2024-08-01 01:29 UTC, dswebsme approved these changes

2024-08-01 01:29 UTC, dswebsme commented on src/block-variations/paragraph/edit.js
> +					className={[
Recommend space between { and [. Good otherwise! Approved.

2024-08-06 12:31 UTC, iwatkinshpu approved these changes

2024-08-06 12:46 UTC, merged